### ISSUE TITLE
Dataherald integration

### ISSUE THREAD

**Issue by MohammadrezaPourreza** [amoffat/HeimdaLLM#12]
Hello,

I trust you're doing well. I'm Mohammadreza Pourreza, a software architect at Dataherald. I'm reaching out to explore the possibility of collaboration. Would you be open to discussing this further? You can reach me at mohammadreza@dataherald.com. Please don't hesitate to get in touch if you're interested.

**Comment by amoffat** [comment]
Thanks @MohammadrezaPourreza. I've followed up with you over email :+1:
